// ─── Services ────────────────────────────────────────────────────────────────
export const services = [
  {
    id: "hvac",
    slug: "hvac-systems",
    icon: "Wind",
    title: "HVAC Systems",
    shortDesc:
      "End-to-end HVAC design, installation, and commissioning for pharmaceutical plants, hospitals, and industrial facilities — built for regulatory compliance and lifetime reliability.",
    fullDesc:
      "Our HVAC solutions are designed by ISHRAE and ASHRAE-certified engineers who understand the critical importance of air quality in pharmaceutical and healthcare environments. We deliver systems that meet WHO-GMP, US-FDA, and EU-GMP standards.",
    specs: [
      "Dew point control down to -40°C",
      "HEPA H14 filtration (≥99.995% efficiency)",
      "Laminar and turbulent airflow design",
      "AHU selection and duct design per ASHRAE 62.1",
      "Energy-optimized VRF/VRV systems",
      "BMS integration and SCADA monitoring",
    ],
    standards: ["ISO 14644", "WHO-GMP", "US-FDA 21 CFR Part 11", "ASHRAE 62.1"],
    image: "/images/projects/project-2.png",
    keyApplications: [
      "Pharmaceutical manufacturing",
      "Cleanroom HVAC",
      "Hospital & healthcare",
    ],
  },
  {
    id: "cleanroom",
    slug: "cleanroom-solutions",
    icon: "Shield",
    title: "Cleanroom Solutions",
    shortDesc:
      "Turnkey cleanroom design, construction, and validation for pharmaceutical manufacturing and sterile fill-finish — zero audit failures, guaranteed.",
    fullDesc:
      "We design, construct, and validate cleanrooms to ISO 14644 classifications (ISO 5 to ISO 8), delivering fully compliant environments for pharmaceutical API synthesis, sterile fill-finish, medical device manufacturing, and semiconductor fabrication.",
    specs: [
      "ISO 5 to ISO 8 classification",
      "Modular and stick-built construction",
      "PVC, GRP, and powder-coated steel panels",
      "Positive and negative pressure cascades",
      "Air shower and pass-box integration",
      "Particle count validation per ISO 14644-1",
    ],
    standards: ["ISO 14644-1/2", "EU-GMP Annex 1", "NADCA standards", "cGMP"],
    image: "/images/projects/project-3.png",
    keyApplications: [
      "Pharma manufacturing",
      "Sterile fill-finish",
      "Medical device production",
    ],
  },
  {
    id: "bim",
    slug: "bim-modelling",
    icon: "Layers",
    title: "BIM Modelling",
    shortDesc:
      "Advanced 3D Building Information Modelling for clash detection, MEP coordination, and facility lifecycle management.",
    fullDesc:
      "Our BIM team uses Revit and Navisworks to create LOD 300–400 models that detect clashes before site work begins, reducing change orders and construction delays by up to 40%.",
    specs: [
      "LOD 200 to LOD 500 deliverables",
      "Clash detection and coordination",
      "MEP routing optimisation",
      "As-built model handover",
      "4D construction sequencing",
      "COBie data export for FM",
    ],
    standards: ["ISO 19650", "PAS 1192", "BEP Protocol"],
    image: "/images/projects/project-4.png",
    keyApplications: [
      "Clash detection",
      "MEP coordination",
      "Digital twin creation",
    ],
  },
  {
    id: "bms",
    slug: "bms-electrical",
    icon: "Zap",
    title: "BMS & Electrical",
    shortDesc:
      "Integrated Building Management Systems and complete electrical engineering from concept to commissioning.",
    fullDesc:
      "We design and commission BMS platforms (Schneider EcoStruxure, Siemens Desigo, Honeywell) that give you real-time control of HVAC, lighting, access control, and energy metering from a single pane of glass.",
    specs: [
      "SCADA and HMI panel design",
      "21 CFR Part 11 audit trail compliance",
      "BACnet/Modbus/LON integration",
      "UPS, DG, and LT panel engineering",
      "Energy metering and sub-metering",
      "Alarm management and trending",
    ],
    standards: ["IEC 60364", "IS 732", "21 CFR Part 11", "ASHRAE 135"],
    image: "/images/bms.jpg",
    keyApplications: [
      "SCADA systems",
      "Energy management",
      "Automation controls",
    ],
  },
  {
    id: "pharma",
    slug: "pharmaceutical-engineering",
    icon: "FlaskConical",
    title: "Pharmaceutical Engineering",
    shortDesc:
      "Complete pharma facility engineering — from API block design to sterile zone validation — meeting WHO, US-FDA, and EU-GMP standards.",
    fullDesc:
      "We act as a single point of responsibility for complete pharmaceutical facility projects, including process equipment layout, clean utility systems (WFI, PW, clean steam), and regulatory documentation packages.",
    specs: [
      "Purified Water (PW) and WFI system design",
      "Clean steam generation and distribution",
      "Containment systems for potent APIs (OEL down to 1µg/m³)",
      "Process flow diagram (PFD) and P&ID development",
      "Validation Master Plan (VMP) and DQ/IQ/OQ/PQ protocols",
      "Change control and SOP development",
    ],
    standards: ["WHO TRS 961", "US-FDA 21 CFR Part 210/211", "EU-GMP Vol. 4", "ICH Q9/Q10"],
    image: "/images/projects/project-5.png",
    keyApplications: [
      "API block design",
      "Clean utility systems",
      "Validation protocols",
    ],
  },
  {
    id: "chemical",
    slug: "chemical-plant-engineering",
    icon: "Atom",
    title: "Chemical Plant Engineering",
    shortDesc:
      "Process design, equipment selection, and plant layout for chemical manufacturing with emphasis on safety and efficiency.",
    fullDesc:
      "Our chemical plant engineering team delivers HAZOP-reviewed process designs, equipment datasheets, and full mechanical completion packages for fine chemical, API, and specialty chemical facilities.",
    specs: [
      "Process simulation (HYSYS/CHEMCAD)",
      "HAZOP and LOPA facilitation",
      "Pressure vessel and heat exchanger design",
      "Piping stress analysis",
      "Relief valve sizing and flare design",
      "Safety instrumented system (SIS) design",
    ],
    standards: ["ASME B31.3", "API 510/570", "OSHA PSM", "IS 2825"],
    image: "/images/chiller.jpg",
    keyApplications: [
      "Process simulation",
      "Safety systems",
      "Equipment engineering",
    ],
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const products = [
  {
    id: "electrical-panel",
    slug: "electrical-panel",
    title: "ELECTRICAL PANEL",
    manufacturer: "Thermopharm",
    category: "Automation & Electrical",
    description: "Custom engineered, powder-coated power control centers (PCC), motor control centers (MCC), and VFD panels engineered for HVAC and cleanroom installations.",
    image: "/images/plc.jpg",
    specs: ["IP 54/65 protection class", "Schneider / Siemens switchgear inside", "Fully integrated PLC/HMI interface", "21 CFR Part 11 compliant audit logging"],
  },
  {
    id: "pre-fabricated-ducting",
    slug: "pre-fabricated-ducting",
    title: "PRE-FABRICATED DUCTING",
    manufacturer: "Thermopharm",
    category: "Air Distribution",
    description: "Precision CNC pre-fabricated GI, SS 304, and SS 316 air ducting with factory-applied insulation for zero-leakage cleanroom air transport.",
    image: "/images/projects/project-2.png",
    specs: ["SMACNA leakage class 3 compliant", "Double-skin insulated construction", "Antibacterial food-grade internal coating", "Precision flange joint systems"],
  },
  {
    id: "cleanroom-filters",
    slug: "cleanroom-filters",
    title: "CLEANROOM FILTERS",
    manufacturer: "Thermopharm",
    category: "Filtration Systems",
    description: "High-efficiency HEPA (H13/H14) and ULPA (U15) terminal filter modules engineered specifically for pharmaceutical sterile zones and ISO 1-8 cleanrooms.",
    image: "/images/projects/project-3.png",
    specs: ["≥99.995% efficiency @ 0.3 micron", "Anodized aluminum extrusion frame", "Integral gel seal or neoprene gasket", "Individual DOP/PAO scan leak certificate"],
  },
  {
    id: "heater-section",
    slug: "heater-section",
    title: "HEATER SECTION",
    manufacturer: "Thermopharm",
    category: "Thermal Control",
    description: "Heavy-duty pre-fabricated electric and steam coil heater sections designed for industrial AHU air reheat and humidity control.",
    image: "/images/chiller.jpg",
    specs: ["SS 304 finned tubular heating elements", "Multi-stage SCR thyristor control", "Overheat cutout & airflow interlock switch", "Flameproof Ex-d enclosure options"],
  },
  {
    id: "diffuser",
    slug: "diffuser",
    title: "DIFFUSER",
    manufacturer: "Thermopharm",
    category: "Terminal Air Outlets",
    description: "Sleek swirl, perforated, and 4-way supply air diffusers for pharmaceutical Grade A-D suites and high-end comfort zones.",
    image: "/images/projects/project-4.png",
    specs: ["Powder coated extruded aluminum / SS 304", "Removable core for easy duct access", "Integral opposed blade damper", "Flush ceiling aesthetic finish"],
  },
  {
    id: "grills",
    slug: "grills",
    title: "GRILLS",
    manufacturer: "Thermopharm",
    category: "Terminal Air Outlets",
    description: "Heavy-gauge Stainless Steel (SS 304/316) return air and filter grills engineered for cleanroom washability and zero corrosion.",
    image: "/images/projects/project-5.png",
    specs: ["Mirror or satin polish SS 304/316", "Integrated EU4 / G4 pre-filter frame", "Single / double deflection adjustable louvers", "Easy click-lock release mechanism"],
  },
];

// ─── Completed Projects ────────────────────────────────────────────────────────
export const projects = [
  {
    id: "aims-ernakulam",
    slug: "aims-ernakulam",
    title: "AIMS Medical & Cleanroom Infrastructure",
    client: "Amrita Institute of Medical Sciences (AIMS)",
    location: "Ernakulam, Kerala",
    year: "2024",
    category: "Healthcare",
    tags: ["Healthcare", "Cleanroom", "HVAC", "NABH"],
    description: "Turnkey HVAC, sterile operating theatre suite, and positive pressure cleanroom isolation wards for premier multi-specialty institute.",
    challenge: "Maintaining stringent positive pressurization across multi-floor surgical blocks during continuous patient intake.",
    solution: "Installed dedicated AHUs with HEPA terminal filters and continuous differential pressure monitoring.",
    results: ["Zero post-operative infection incidents", "NABH standard compliance achieved", "Energy optimized chilled water network"],
    image: "/images/projects/project-1.png",
    gallery: ["/images/projects/picture-1.jpg"],
  },
  {
    id: "ammro-dairy",
    slug: "ammro-dairy",
    title: "AMMRO Dairy Processing Clean Air Facility",
    client: "AMMRO Dairy",
    location: "Ernakulam, Kerala",
    year: "2024",
    category: "Food & Beverage",
    tags: ["Dairy", "Clean Air", "HVAC", "ISO 14644"],
    description: "High-grade hygienic air handling and positive pressure packaging zone design to prevent bacterial contamination.",
    challenge: "High ambient humidity and stringent food safety moisture controls in dairy processing zones.",
    solution: "Custom de-humidification coil AHUs combined with antibacterial GI ductwork and micro-filtration.",
    results: ["Shelf-life extension of dairy products", "100% microbial compliance in air samples"],
    image: "/images/projects/project-2.png",
    gallery: ["/images/projects/picture-2.jpg"],
  },
  {
    id: "iol-chemical",
    slug: "iol-chemical",
    title: "IOL Chemical API & Process Plant HVAC",
    client: "IOL Chemicals and Pharmaceuticals Ltd.",
    location: "Ambala, Punjab",
    year: "2023",
    category: "Pharmaceutical",
    tags: ["API", "Chemical", "HVAC", "USFDA"],
    description: "Complete API block environmental control, hazardous fume exhaust, and clean utility design for large scale manufacturing.",
    challenge: "Handling corrosive solvent fumes and dust extraction in high-potency chemical blocks.",
    solution: "Flameproof SS 316 exhaust fans, wet scrubbers, and 21 CFR Part 11 compliant SCADA BMS.",
    results: ["Zero solvent exposure levels", "Passed international cGMP quality audits"],
    image: "/images/projects/project-3.png",
    gallery: [],
  },
  {
    id: "niper-hyderabad",
    slug: "niper-hyderabad",
    title: "NIPER Biomedical Research Cleanroom",
    client: "National Institute of Pharmaceutical Education & Research",
    location: "Hyderabad, Telangana",
    year: "2023",
    category: "BSL-3",
    tags: ["R&D", "BSL-3", "Biomedical", "Containment"],
    description: "ISO 5 containment laboratory with 100% fresh air single pass HVAC and double-HEPA exhaust filtration.",
    challenge: "Extreme negative pressure requirements with fail-safe automatic fan switchover.",
    solution: "Installed dual redundant centrifugal exhaust fans with UPS battery backup and instant alarms.",
    results: ["Certified for national biomedical research", "Passed CDC containment guidelines"],
    image: "/images/projects/project-4.png",
    gallery: [],
  },
  {
    id: "niper-kolkata",
    slug: "niper-kolkata",
    title: "NIPER Advanced R&D Clean Lab",
    client: "National Institute of Pharmaceutical Education & Research",
    location: "Kolkata, West Bengal",
    year: "2023",
    category: "BSL-3",
    tags: ["R&D", "Pharma", "Cleanroom", "ISO 6"],
    description: "Modular cleanroom facility for drug delivery development and nanotechnology research.",
    challenge: "Vibration sensitive laser optical table positioning requiring zero micro-vibrations from AHUs.",
    solution: "Spring isolated AHU pads and remote duct attenuators with precision temperature control (±0.5°C).",
    results: ["Sub-micron optical alignment preserved", "ISO 6 cleanroom certification"],
    image: "/images/projects/project-5.png",
    gallery: [],
  },
  {
    id: "suprima-cosmo-tech",
    slug: "suprima-cosmo-tech",
    title: "Suprima Cosmo Tech Precision Cleanroom",
    client: "Suprima Cosmo Tech",
    location: "Ambernath, Mumbai",
    year: "2023",
    category: "Industrial",
    tags: ["Industrial", "Cleanroom", "ESD", "HVAC"],
    description: "Turnkey ESD cleanroom for precision electronic packaging and high-tech cosmeceutical formulations.",
    challenge: "Static charge buildup and particulate control in high-speed filling lines.",
    solution: "ESD anti-static epoxy flooring, ionized air curtain pass boxes, and ISO 7 HEPA modules.",
    results: ["Static discharge risk eliminated", "Product yield increased by 22%"],
    image: "/images/projects/project-1.png",
    gallery: [],
  },
  {
    id: "globela-pharma",
    slug: "globela-pharma",
    title: "Globela Pharma Sterile Export Suite",
    client: "Globela Pharma Pvt. Ltd.",
    location: "Surat, Gujarat",
    year: "2023",
    category: "Pharmaceutical",
    tags: ["Export GMP", "Sterile Fill", "HVAC", "EU-GMP"],
    description: "Turnkey formulation cleanrooms meeting EU-GMP Annex 1 guidelines for sterile injectable export.",
    challenge: "Strict RH control (<40%) in Surat's coastal monsoon climate.",
    solution: "Desiccant dehumidification wheel integrated with 10,000 CFM chilled water AHU.",
    results: ["EU-GMP audit success", "RH maintained continuously at 35%"],
    image: "/images/projects/project-2.png",
    gallery: [],
  },
  {
    id: "livguard-pune",
    slug: "livguard-pune",
    title: "Livguard Battery & Energy Storage Cleanroom",
    client: "Livguard Energy Technologies",
    location: "Pune, Maharashtra",
    year: "2022",
    category: "Solar",
    tags: ["Energy", "ESD", "Ultra-low Humidity", "Cleanroom"],
    description: "Ultra-low humidity dry room (<1% RH) for advanced lithium cell assembly and battery manufacturing.",
    challenge: "Maintaining dew point down to -40°C in continuous operation.",
    solution: "Seibu Giken desiccant wheel dry room system with hermetically sealed wall panels.",
    results: ["Achieved -45°C dew point", "Zero cell degradation during assembly"],
    image: "/images/projects/project-3.png",
    gallery: [],
  },
  {
    id: "globela-industries",
    slug: "globela-industries",
    title: "Globela Industries Fine Chemical HVAC",
    client: "Globela Industries",
    location: "Bharuch, Gujarat",
    year: "2022",
    category: "Chemical",
    tags: ["Chemical", "Fume Exhaust", "HVAC", "Safety"],
    description: "Process plant ventilation, toxic gas scrubber integration, and explosion-proof electrical design.",
    challenge: "Hazardous Class 1 Div 1 explosive atmosphere requiring ATEX compliance.",
    solution: "ATEX certified explosion-proof motors, spark-proof fan impellers, and stainless ducting.",
    results: ["Passed safety hazard audit", "100% airborne containment of chemical vapors"],
    image: "/images/projects/project-4.png",
    gallery: [],
  },
  {
    id: "shah-brothers",
    slug: "shah-brothers",
    title: "Shah Brothers Logistics & Clean Storage",
    client: "Shah Brothers",
    location: "Bhiwandi, Mumbai",
    year: "2022",
    category: "Industrial",
    tags: ["Logistics", "Cold Chain", "HVAC", "Warehouse"],
    description: "Controlled temperature warehouse (15-25°C) and cold storage rooms (2-8°C) for pharma distribution.",
    challenge: "Large volume warehouse space with high ceiling heat gain during Mumbai summers.",
    solution: "High-throw jet diffusers and VRF chilled water system with IoT temperature mapping.",
    results: ["Uniform temperature across 40,000 sq ft", "WHO GDP compliance achieved"],
    image: "/images/projects/project-5.png",
    gallery: [],
  },
  {
    id: "tata-consumer",
    slug: "tata-consumer",
    title: "Tata Consumer Products Clean Packaging Unit",
    client: "Tata Consumer Products Ltd.",
    location: "Hebbal, Bangalore",
    year: "2022",
    category: "Food & Beverage",
    tags: ["Food Grade", "HVAC", "Cleanroom", "FSSAI"],
    description: "Hygienic food packaging cleanroom with positive pressurization and HEPA filtration.",
    challenge: "Preventing micro-particulate contamination during high-speed tea and spice blending.",
    solution: "Positive pressure cascade with stainless steel washable ceiling panels and HEPA filtration.",
    results: ["FSSAI hygiene audit score 99/100", "Zero dust buildup on automated lines"],
    image: "/images/projects/project-1.png",
    gallery: [],
  },
  {
    id: "kcpl-turbhe",
    slug: "kcpl-turbhe",
    title: "KCPL Specialty Chemical & Cleanroom Facility",
    client: "KCPL Chemical",
    location: "Turbhe, Mumbai",
    year: "2021",
    category: "Chemical",
    tags: ["Chemical", "Cleanroom", "HVAC"],
    description: "Cleanroom and specialized air handling for active ingredient packaging.",
    challenge: "Cross-contamination prevention between multi-product synthesis lines.",
    solution: "Independent AHUs per block with dedicated pass boxes and interlock doors.",
    results: ["Cross-contamination risk zeroed", "Operational efficiency up 18%"],
    image: "/images/projects/project-2.png",
    gallery: [],
  },
  {
    id: "hershey-bhopal",
    slug: "hershey-bhopal",
    title: "Hershey Confectionery Clean HVAC System",
    client: "Hershey India",
    location: "Bhopal, Madhya Pradesh",
    year: "2021",
    category: "Food & Beverage",
    tags: ["Confectionery", "Chilled Water", "HVAC", "ISO 22000"],
    description: "Process cooling and clean air conditioning for chocolate molding and packaging halls.",
    challenge: "Strict relative humidity control (<45% RH) to prevent sugar bloom on chocolate product lines.",
    solution: "Precision chilled water AHUs with secondary cooling coils and BACnet BMS control.",
    results: ["Sugar bloom defects eliminated", "24/7 continuous operation without downtime"],
    image: "/images/projects/project-3.png",
    gallery: [],
  },
  {
    id: "hanuchem-parwanoo",
    slug: "hanuchem-parwanoo",
    title: "Hanuchem Sterile Formulations Facility",
    client: "Hanuchem Laboratories",
    location: "Parwanoo, Himachal Pradesh",
    year: "2021",
    category: "Pharmaceutical",
    tags: ["Formulations", "Sterile", "Cleanroom", "WHO-GMP"],
    description: "Grade A laminar airflow workstation and Grade B cleanrooms for liquid injectables.",
    challenge: "Extreme winter temperature drops requiring reliable dual heating/cooling coils.",
    solution: "Hot water heating coils combined with DX cooling and automatic winter/summer changeover.",
    results: ["WHO-GMP audit cleared", "Stable year-round room temperature"],
    image: "/images/projects/project-4.png",
    gallery: [],
  },
  {
    id: "vip-baddi",
    slug: "vip-baddi",
    title: "VIP Pharma Formulations Facility",
    client: "VIP Pharma",
    location: "Baddi, Haryana",
    year: "2020",
    category: "Pharmaceutical",
    tags: ["Formulations", "HVAC", "Tablet Block", "Cleanroom"],
    description: "Turnkey HVAC for solid dosage tablet and capsule manufacturing block.",
    challenge: "High dust generation during powder compression and tablet coating.",
    solution: "Dust extraction hoods coupled to reverse pulse jet bag filters and HEPA return AHUs.",
    results: ["Worker health safety assured", "Cleanroom air quality Grade D maintained"],
    image: "/images/projects/project-5.png",
    gallery: [],
  },
];

// ─── Team ─────────────────────────────────────────────────────────────────────
export const team = [
  {
    name: "Ashish Jha",
    role: "Founder & Director",
    bio: "Visionary engineering leader at ThermoPharm, specializing in turnkey HVAC, pharmaceutical cleanroom design, and complex facility infrastructure across India.",
    image: "/images/team/ashish-jha.jpeg",
    email: "Info@thermopharm.in",
    linkedin: "https://www.linkedin.com/in/ashish-jha-07024316b?originalSubdomain=in",
  },
  {
    name: "Sudip Yadav",
    role: "Design Manager",
    bio: "Head of engineering design & BIM coordination. Expertise in LOD 400 MEP modelling, air cascade optimization, and ASHRAE/ISO compliant facility layouts.",
    image: "/images/team/Sudip Yadav.jpg",
    linkedin: "https://www.linkedin.com/in/sudip-yadav/",
  },
  {
    name: "Khushbu Jha",
    role: "Director",
    bio: "Executive Director overseeing strategic growth, client partnerships, quality management systems, and organizational operations at ThermoPharm.",
    image: "/images/team/Khushbu Jha.jpeg",
    linkedin: "#",
  },
];

// ─── Clients / Trust bar (with logo images) ────────────────────────────────────
export const clients = [
  "AIIMS", "AMMRO DAIRY", "IOL CHEMICAL", "NIPER", "SUPRA COSMO TECH",
  "GLOBELA PHARMA", "LIVGUARD", "SHAH BROTHERS", "KCPL", "HERSHEY",
  "HANUCHEM", "VIP",
];

export const clientLogos = [
  { name: "AMIS", logo: "/images/clients/amis.png" },
  { name: "AMMRO DAIRY", logo: "/images/clients/ammro-dairy.png" },
  { name: "HERSHEY", logo: "/images/clients/hershey-logo.png" },
  { name: "KCPL", logo: "/images/clients/kcpl.png" },
  { name: "LIVGUARD", logo: "/images/clients/livguard.png" },
  { name: "SHAH BROTHERS", logo: "/images/clients/shah-brothers.png" },
  { name: "SUPRIMA", logo: "/images/clients/suprima.png" },
  { name: "VIP PHARMA", logo: "/images/clients/vip-pharma.png" },
];

// ─── Blog posts ───────────────────────────────────────────────────────────────
export const blogPosts = [
  {
    id: "iso-14644-guide",
    slug: "understanding-iso-14644-cleanroom-standards",
    title: "Understanding ISO 14644 Cleanroom Standards: A Complete Guide",
    excerpt:
      "ISO 14644 is the global benchmark for cleanroom classification and monitoring. This guide breaks down every clause you need to know before designing or qualifying your facility.",
    date: "2024-01-15",
    author: "Ashish Jha",
    category: "Cleanroom",
    readTime: "8 min read",
    image: "/images/projects/project-3.png",
    content: `ISO 14644 is a multi-part standard that defines cleanroom classification, monitoring, and design requirements. Understanding its structure is essential for any pharmaceutical or semiconductor facility engineer.\n\n## Part 1: Classification\n\nISO 14644-1 defines cleanliness classes based on airborne particle counts per cubic metre. The most common classes used in pharma are ISO 5 (Grade A/B) and ISO 7/8 (Grade C/D).\n\n## Part 2: Monitoring\n\nISO 14644-2 establishes monitoring intervals and methods to maintain classification between full re-qualifications. It specifies the number of sample locations based on room area.\n\n## Design Implications\n\nEvery HVAC system serving a cleanroom must be designed with the ISO class target in mind from day one. Filter efficiency, air change rates, pressurisation strategy, and garment protocols all flow from the classification requirement.`,
    faq: [
      {
        question: "What is the difference between ISO 5 and Grade A/B?",
        answer: "ISO 14644-1 Class 5 corresponds broadly to EU GMP Grade A and Grade B (at-rest). Grade A and B are regulatory classifications under EU GMP Annex 1, while ISO classes are based purely on particle counts per cubic metre.",
      },
      {
        question: "How often must cleanrooms be re-qualified under ISO 14644?",
        answer: "ISO 14644-2 recommends re-qualification at least every 12 months for ISO Classes 5–8 in typical pharmaceutical applications, though GMP regulations may require more frequent monitoring based on risk assessment.",
      },
      {
        question: "Who performs the classification testing?",
        answer: "Classification testing should be performed by a third-party accredited laboratory (NABL/UKAS accredited) or a competent in-house team using calibrated, certified particle counters.",
      },
    ],
  },
  {
    id: "bim-cleanroom",
    slug: "benefits-of-bim-in-cleanroom-design",
    title: "Benefits of BIM in Cleanroom Design: Reducing Cost and Risk",
    excerpt:
      "Building Information Modelling (BIM) has transformed cleanroom and pharmaceutical facility design. Here's how LOD 300+ models prevent costly on-site surprises.",
    date: "2024-02-20",
    author: "Sudip Yadav",
    category: "BIM",
    readTime: "6 min read",
    image: "/images/projects/project-4.png",
    content: `BIM adoption in cleanroom projects has proven to reduce construction rework by up to 40% and cut project delivery timelines by 15–20%. Here's why every pharma facility owner should demand BIM from their engineering partner.\n\n## Clash Detection Saves Lakhs\n\nIn a typical cleanroom project, HVAC ductwork, piping, electrical cable trays, and structure all compete for the same ceiling plenum space. Without BIM, these clashes are discovered during site work — at enormous cost. With Navisworks clash detection, conflicts are resolved on screen before a single hammer swings.\n\n## As-Built Models for FM\n\nA LOD 500 as-built BIM model handed over at project close gives your facility management team a digital twin of your plant. Every valve, damper, and filter has a location, specification, and maintenance schedule embedded in the model.`,
    faq: [
      {
        question: "What LOD (Level of Development) is required for cleanroom projects?",
        answer: "For detailed design and clash detection, LOD 300 is the minimum. For construction and handover, LOD 400 (fabrication-ready) is recommended. For facility management digital twins, LOD 500 (as-built) should be specified.",
      },
      {
        question: "Does BIM add significant cost to my project?",
        answer: "BIM modelling typically adds 2–4% to engineering fees but saves 8–15% of total project cost through reduced rework, fewer RFIs, and faster construction. The ROI is consistently positive on projects over ₹2 Crore.",
      },
    ],
  },
];

// ─── Company Info ─────────────────────────────────────────────────────────────
export const companyInfo = {
  name: "Thermopharm Pvt. Ltd.",
  tagline: "An engineering company for tomorrow",
  description:
    "Mumbai-based HVAC and cleanroom engineering specialist delivering end-to-end facility solutions for pharmaceutical, healthcare, and industrial sectors since 2018.",
  phone: "+91 63 9663 3736",
  email: "Info@thermopharm.in",
  address: "Office No 319, Infinity Square Building, Chinchpada, Vasai East, Mumbai — 401208",
  certifications: ["ISHRAE Member", "ASHRAE Member", "GMP Certified"],
  stats: [
    { value: "6+", label: "Years Experience" },
    { value: "250+", label: "Projects Delivered" },
    { value: "100%", label: "Client Satisfaction" },
    { value: "0", label: "Audit Failures" },
  ],
  socialLinks: {
    linkedin: "https://www.linkedin.com/in/ashish-jha-07024316b?originalSubdomain=in",
    email: "mailto:Info@thermopharm.in",
  },
};

// ─── Navigation ───────────────────────────────────────────────────────────────
export const navLinks = [
  { label: "About Us", href: "/about" },
  {
    label: "Services",
    href: "/services",
    children: services.map((s) => ({ label: s.title, href: `/services/${s.slug}` })),
  },
  { label: "Products", href: "/products" },
  { label: "Industries", href: "/industries" },
  { label: "Projects", href: "/projects" },
  { label: "Clients", href: "/clients" },
  { label: "Blog", href: "/blog" },
];

// ─── Homepage FAQ ──────────────────────────────────────────────────────────────
export const homepageFaq = [
  {
    question: "What industries does Thermopharm serve?",
    answer:
      "We serve pharmaceutical manufacturing (API, formulation, sterile fill-finish), biotech, hospitals and healthcare, chemical plants, food processing, semiconductor fabrication, and solar panel manufacturing.",
  },
  {
    question: "Are your cleanrooms WHO-GMP and US-FDA compliant?",
    answer:
      "Yes. All cleanroom and HVAC systems we design are compliant with WHO TRS 961, US-FDA 21 CFR Part 210/211, EU-GMP Annex 1, and ISO 14644. Our validation engineers prepare complete DQ/IQ/OQ/PQ documentation packages.",
  },
  {
    question: "Do you offer turnkey project execution?",
    answer:
      "Yes. We offer end-to-end services from initial concept design, detailed engineering, procurement, supply, installation, commissioning, qualification, and ongoing AMC support — all under one contract.",
  },
  {
    question: "What is your project turnaround time?",
    answer:
      "Typical HVAC-only projects take 3–6 months from design to commissioning. Turnkey cleanroom projects typically take 8–12 months depending on scope. We provide detailed project schedules at the proposal stage.",
  },
  {
    question: "Where are you based and which geographies do you serve?",
    answer:
      "Our head office is in Vasai East, Mumbai. We have executed projects across Maharashtra, Gujarat, Telangana, Haryana, and Rajasthan, and we have a growing presence in East Africa.",
  },
];
